export const initialTodoList: TodoList = [
  {
    id: '1',
    name: 'Create Todo project',
    description: `It's due to complete this task ASAP`,
    priority: 1,
    complete: false,
  },
  {
    id: '2',
    name: 'Run 5km, please',
    description: `Important for current week`,
    priority: 2,
    complete: true,
  },
  {
    id: '3',
    name: 'Smile and go on',
    description: `Always helps`,
    priority: 1,
    complete: false,
  },
  {
    id: '4',
    name: 'Drink water - 2 liters',
    description: `Doctors recommend`,
    priority: 1,
    complete: false,
  },
  {
    id: '5',
    name: 'Eat something',
    description: `Doctors recommend as well`,
    priority: 2,
    complete: true,
  },
  {
    id: '6',
    name: 'Read a book',
    description: `Pick an interesting one`,
    priority: 2,
    complete: false,
  },
  {
    id: '7',
    name: 'Learn Typescript',
    description: `Otherwise how will you create your Todo project`,
    priority: 1,
    complete: false,
  },
  {
    id: '8',
    name: 'Eat some other thing',
    description: `Yes, need to eat not only once a day`,
    priority: 3,
    complete: true,
  },
  {
    id: '9',
    name: 'Read a another book',
    description: `Become better every day`,
    priority: 3,
    complete: false,
  },
];
